version: '3.4'

services:
  db:
    image: postgres
    container_name: spt_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mainDB
    volumes:
      # Ensure we make our initialization scripts accessible
      - ./storage/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  backend:
    image: confused-techie/spt:1.5
    container_name: spt_be
    depends_on:
      db:
        condition: service_started
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: password
      DB_DB: mainDB
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./storage:/usr/src/app/storage
