version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mainDB
    volumes:
      # Ensure we make our initialization scripts accessible
      - ./storage/sql:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  backend:
    image: confused-Techie/student-point-tracker@latest
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DB: mainDB
      DB_HOST: "localhost:5432"
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./storage:/usr/src/app/storage
