name: 'VersionCheck'
description: 'See if the "package.json" version has changed recently.'
inputs:
  debug:
    default: false
    required: false
    description: 'Wether or not to enable debug logging.'
outputs:
  changed:
    description: 'If the "package.json" version key changed in the last commit.'
  version:
    description: 'What the version has changed too.'
runs:
  using: 'node20'
  main: 'index.js'
