name: Standards

on:
  push:
    branches:
      - "main"

jobs:
  standards:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v4

    - name: Setup NodeJS - ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Lint Codebase
      run: npm run lint

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: CI Standards Applied
